ServerHTTPConfig:
  host: localhost #empty
  port: 8080

DatabaseConfig:
  host: localhost #localhost # mongodb
  port: 27017
  name: device_manager

KafkaConfig:
  brokers: localhost:9092 # kafka:9092
  group: "group"

LoggerConfig:
  encoding: json
  level: info
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: message
    levelKey: level
    timeKey: time
    timeEncoder: ISO8601
    levelEncoder: capital
    durationEncoder: string
    callerEncoder: short
